package br.com.senac.hortadidatica.gui.Aula;

import br.com.senac.hortadidatica.persistencia.DAO;
import br.com.senac.hortadidatica.persistencia.DadoAula;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danilo
 */
public class telaAdicionarRoteiroAula extends javax.swing.JFrame {

public telaAdicionarRoteiroAula() {
        initComponents();
        geraAcessbilidadeAdicionarAula();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAulaTitulo = new javax.swing.JTextField();
        txtAulaTempo = new javax.swing.JTextField();
        txtAulaMaterial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAulaObjetivo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAulaProcedimento = new javax.swing.JTextArea();
        btnAdicionarAulaVoltar = new javax.swing.JButton();
        btnCadastrarAula = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAulaAvaliacao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("ADICIONAR ROTEIRO DE AULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Tempo de aula:");

        jLabel3.setText("Título da aula:");

        jLabel4.setText("Materiais:");

        jLabel5.setText("Objetivos:");

        jLabel6.setText("Procedimentos:");

        txtAulaTitulo.setToolTipText("Digite o título da aula");

        txtAulaTempo.setToolTipText("Digite o tempo da aula em minutos ou horas");

        txtAulaMaterial.setToolTipText("Digite os materiais usados em aula (Plantas, datashow, utensílios, lupa ou microscópio etc.)");

        txtAulaObjetivo.setColumns(20);
        txtAulaObjetivo.setRows(5);
        txtAulaObjetivo.setToolTipText("Digite os objetivos (geral e específicos) da aula");
        jScrollPane1.setViewportView(txtAulaObjetivo);

        txtAulaProcedimento.setColumns(20);
        txtAulaProcedimento.setRows(5);
        txtAulaProcedimento.setToolTipText("Digite os procedimentos da aula");
        jScrollPane2.setViewportView(txtAulaProcedimento);

        btnAdicionarAulaVoltar.setText("Voltar");
        btnAdicionarAulaVoltar.setToolTipText("Voltar para a tela de roteiros de aula (Alt+V)");
        btnAdicionarAulaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAulaVoltarActionPerformed(evt);
            }
        });

        btnCadastrarAula.setText("Cadastrar");
        btnCadastrarAula.setToolTipText("Cadastrar o novo roteiro (Alt+C)");
        btnCadastrarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAulaActionPerformed(evt);
            }
        });

        txtAulaAvaliacao.setColumns(20);
        txtAulaAvaliacao.setRows(5);
        jScrollPane3.setViewportView(txtAulaAvaliacao);

        jLabel7.setText("Avaliação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAulaTempo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAulaMaterial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(txtAulaTitulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionarAulaVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(btnCadastrarAula))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAulaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtAulaTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAulaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarAula)
                    .addComponent(btnAdicionarAulaVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAulaActionPerformed
        // TODO add your handling code here:
        if(!campoVazioAula()){
            
            DadoAula aula = new DadoAula();
            aula.setTituloAula(txtAulaTitulo.getText());
            aula.setTempoAula(txtAulaTempo.getText());
            aula.setMaterialAula(txtAulaMaterial.getText());
            aula.setObjetivoAula(txtAulaObjetivo.getText());
            aula.setProcedimentoAula(txtAulaProcedimento.getText());
            aula.setAvaliacaoAula(txtAulaAvaliacao.getText());
            
            try{
                DAO aulaDao = new DAO();
                aulaDao.cadastrar(aula);
                JOptionPane.showMessageDialog(rootPane, "Aula cadastrada!");
                telaRoteiroAula.iniciaTabelaAula();

            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao cadastrar a aula:\n" + e.getMessage());
            }
        } 

    }//GEN-LAST:event_btnCadastrarAulaActionPerformed

    private void btnAdicionarAulaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAulaVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnAdicionarAulaVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAdicionarRoteiroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAdicionarRoteiroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAdicionarRoteiroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAdicionarRoteiroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAdicionarRoteiroAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAulaVoltar;
    private javax.swing.JButton btnCadastrarAula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAulaAvaliacao;
    private javax.swing.JTextField txtAulaMaterial;
    private javax.swing.JTextArea txtAulaObjetivo;
    private javax.swing.JTextArea txtAulaProcedimento;
    private javax.swing.JTextField txtAulaTempo;
    private javax.swing.JTextField txtAulaTitulo;
    // End of variables declaration//GEN-END:variables

private boolean campoVazioAula(){

    boolean empty = true; 

    if(txtAulaTitulo.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! O título da aula deve ser preenchido!");    
    } else if(txtAulaTempo.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Informar o tempo de aula!");   
    } else if(txtAulaMaterial.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Informar os materiais usados na aula (plantas, pinças, microscópio etc.");     
    } else if(txtAulaObjetivo.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Informar os objetivos (geral e específicos) da aula");     
    } else if(txtAulaProcedimento.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Informar os procedimentos da aula");     
    }else if(txtAulaAvaliacao.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Informar o método de avaliação da aula");     
    }else{
         empty = false;
    }
     return empty;    
    }

public void geraAcessbilidadeAdicionarAula(){

btnCadastrarAula.setMnemonic(KeyEvent.VK_C);
btnAdicionarAulaVoltar.setMnemonic(KeyEvent.VK_V);
    
}


}
