package br.com.senac.hortadidatica.gui.Aula;

import br.com.senac.hortadidatica.persistencia.DAO;
import br.com.senac.hortadidatica.persistencia.DadoAula;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danilo
 */
public class telaRoteiroAula extends javax.swing.JFrame {

    /**
     * Creates new form telaRoteiroAula
     */
    
        //Passo A
    public static final String[] tableColumnsAula = {"Nome do roteiro"};
    
    //Passo A2
    public static DefaultTableModel tableModelAula = new DefaultTableModel(tableColumnsAula, 0);
    
    public telaRoteiroAula() {
        initComponents();
        geraAcessbilidadeAula();
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) {
            iniciaTabelaAula();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnVerRoteiro = new javax.swing.JButton();
        btnAdicionarRoteiro = new javax.swing.JButton();
        btnExcluirRoteiro = new javax.swing.JButton();
        btnRoteiroVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoteiroAula = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("ROTEIROS DE AULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu Aulas"));

        btnVerRoteiro.setText("Ver Roteiro");
        btnVerRoteiro.setToolTipText("Clique aqui para ver um dos roteiros ao lado (Alt + R)");
        btnVerRoteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRoteiroActionPerformed(evt);
            }
        });

        btnAdicionarRoteiro.setText("Adicionar");
        btnAdicionarRoteiro.setToolTipText("Clique aqui para adicionar um novo roteiro de aula (Alt + A)");
        btnAdicionarRoteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarRoteiroActionPerformed(evt);
            }
        });

        btnExcluirRoteiro.setText("Excluir");
        btnExcluirRoteiro.setToolTipText("Clique aqui para excluir um dos roteiros de aula ao lado (Alt + E)");
        btnExcluirRoteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirRoteiroActionPerformed(evt);
            }
        });

        btnRoteiroVoltar.setText("Voltar");
        btnRoteiroVoltar.setToolTipText("Voltar ao menu inicial (Alt + V)");
        btnRoteiroVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoteiroVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirRoteiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionarRoteiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerRoteiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRoteiroVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerRoteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarRoteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirRoteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnRoteiroVoltar)
                .addContainerGap())
        );

        tblRoteiroAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Nome do Roteiro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRoteiroAula);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoteiroVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoteiroVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnRoteiroVoltarActionPerformed

    private void btnVerRoteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRoteiroActionPerformed
        // TODO add your handling code here:
        String posicaoTabelaAula = getPosicaoTabelaAula();

    if (!posicaoTabelaAula.equals("-1")) {
        DadoAula aulaSelecionada = DAO.obterPorId(DadoAula.class, posicaoTabelaAula);

        telaVerRoteiroAula TelaVerRoteiroAula = new telaVerRoteiroAula();

        TelaVerRoteiroAula.txtVerNomeAula.setText(aulaSelecionada.getTituloAula());
        TelaVerRoteiroAula.txtVerTempoAula.setText(aulaSelecionada.getTempoAula());
        TelaVerRoteiroAula.txtVerMaterialAula.setText(aulaSelecionada.getMaterialAula());
        TelaVerRoteiroAula.txtVerObjetivoAula.setText(aulaSelecionada.getObjetivoAula());
        TelaVerRoteiroAula.txtVerProcedimentoAula.setText(aulaSelecionada.getProcedimentoAula());
        TelaVerRoteiroAula.txtVerAvaliacaoAula.setText(aulaSelecionada.getAvaliacaoAula());

        TelaVerRoteiroAula.setVisible(true);
        
    } else {
        JOptionPane.showMessageDialog(null, "Selecione uma aula!");
    }  
    }//GEN-LAST:event_btnVerRoteiroActionPerformed

    private void btnAdicionarRoteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarRoteiroActionPerformed
        // TODO add your handling code here:
        telaAdicionarRoteiroAula AdicionarRoteiroAula = new telaAdicionarRoteiroAula(); 
        AdicionarRoteiroAula.setVisible(true);
    }//GEN-LAST:event_btnAdicionarRoteiroActionPerformed

    private void btnExcluirRoteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirRoteiroActionPerformed
        // TODO add your handling code here:
       if(!getPosicaoTabelaAula().equals("-1")){
            
            String[] options = { "Sim", "Não" };
            
            int deletar = JOptionPane.showOptionDialog(
                 rootPane,
                 "Tem certeza que deseja excluir as informações dessa aula?\n(essa ação não pode ser desfeita)", 
                 "Exclusão de aula", 
                 JOptionPane.DEFAULT_OPTION, 
                 JOptionPane.QUESTION_MESSAGE, 
                 null, 
                 options, 
                 options[0]
              
            );
            
            if (deletar == 0){
                DAO.excluir(DadoAula.class,  getPosicaoTabelaAula());
                iniciaTabelaAula();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma aula!");
        }
    }//GEN-LAST:event_btnExcluirRoteiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaRoteiroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaRoteiroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaRoteiroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaRoteiroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaRoteiroAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarRoteiro;
    private javax.swing.JButton btnExcluirRoteiro;
    private javax.swing.JButton btnRoteiroVoltar;
    private javax.swing.JButton btnVerRoteiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblRoteiroAula;
    // End of variables declaration//GEN-END:variables


public static String getPosicaoTabelaAula() {
    int rowIndex = tblRoteiroAula.getSelectedRow();

    if (rowIndex == -1) {
        return "-1";
    } else {
        return String.valueOf(tblRoteiroAula.getValueAt(rowIndex, 0));
    }
}

public static void iniciaTabelaAula(){
    try{
        DAO aulaDao = new DAO();
        List<DadoAula> listaAula = aulaDao.listar(DadoAula.class);
        preencheTabelaAula(listaAula);
    }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu uma falha:\n" + e.getMessage());
    }
}

public static void preencheTabelaAula(List<DadoAula> listaAula){
    String columns[] = {"Id", "Nome do Roteiro"};
    String dados[][] = new String[listaAula.size()][columns.length];
    int i=0;
    for(DadoAula d: listaAula){
        dados[i] = new String[]{
            String.valueOf(d.getId()),
            d.getTituloAula()};
        i++;
        }
    DefaultTableModel tabelaAula = new DefaultTableModel(dados, columns);
    tblRoteiroAula.setModel(tabelaAula);
    TableColumnModel columnModel = tblRoteiroAula.getColumnModel();//essa linha e as próximas escondem a coluna id para a tabela ficar visualmente melhor
    columnModel.getColumn(0).setMinWidth(0);
    columnModel.getColumn(0).setMaxWidth(0);
    columnModel.getColumn(0).setWidth(0);
    }

public void geraAcessbilidadeAula(){

btnVerRoteiro.setMnemonic(KeyEvent.VK_R);
btnAdicionarRoteiro.setMnemonic(KeyEvent.VK_A);
btnExcluirRoteiro.setMnemonic(KeyEvent.VK_E);
btnRoteiroVoltar.setMnemonic(KeyEvent.VK_V);
    
}

}
