/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.hortadidatica.gui.Horta;

import br.com.senac.hortadidatica.persistencia.DAO;
import br.com.senac.hortadidatica.persistencia.DadoItem;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author danilo
 */
public class telaItem extends javax.swing.JFrame {

    /**
     * Creates new form telaItem
     */
    
            //Passo A
    public static final String[] tableColumnsItem = {"Nome", "Descrição"};
    
    //Passo A2
    public static DefaultTableModel tableModelItem = new DefaultTableModel(tableColumnsItem, 0);
    
    public telaItem() {
        initComponents();
        geraAcessbilidadeItem();
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) {
            iniciaTabelaItem();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAlterarItem = new javax.swing.JButton();
        btnExcluirItem = new javax.swing.JButton();
        btnVoltarHorta = new javax.swing.JButton();
        btnVerDescrição = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnAdicionarItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("ITENS DA HORTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu item"));

        btnAlterarItem.setText("Alterar dados");
        btnAlterarItem.setToolTipText("Clque aqui para adicionar um item da horta (Alt + A)");
        btnAlterarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarItemActionPerformed(evt);
            }
        });

        btnExcluirItem.setText("Excluir");
        btnExcluirItem.setToolTipText("Clique aqui para excluir um item da horta (Alt + E)");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        btnVoltarHorta.setText("Voltar");
        btnVoltarHorta.setToolTipText("Clique aqui para retornar ao menu de acompanhar horta (Alt + V)");
        btnVoltarHorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarHortaActionPerformed(evt);
            }
        });

        btnVerDescrição.setText("Ver descrição");
        btnVerDescrição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDescriçãoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltarHorta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVerDescrição)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDescrição)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(btnVoltarHorta)
                .addContainerGap())
        );

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Quantidade", "Preço", "Preço total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItem);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar item"));

        jLabel2.setText("Nome:");

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Preço:");

        btnAdicionarItem.setText("Adicionar");
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdicionarItem, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionarItem))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarItemActionPerformed
        // TODO add your handling code here:
        String posicaoTabelaItem = getPosicaoTabelaItem();

    if (!posicaoTabelaItem.equals("-1")) {
        DadoItem itemSelecionado = DAO.obterPorId(DadoItem.class, posicaoTabelaItem);

        telaAlterarItem TelaAlterarItem = new telaAlterarItem();

        TelaAlterarItem.txtAlterarItemNome.setText(itemSelecionado.getNomeItem());
        TelaAlterarItem.txtAlterarQuantidade.setText(String.valueOf(itemSelecionado.getQuantidadeItem()));
        TelaAlterarItem.txtAlterarPreco.setText(String.valueOf(itemSelecionado.getPrecoItem()));

        TelaAlterarItem.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Selecione uma planta!");
    } 
    }//GEN-LAST:event_btnAlterarItemActionPerformed

    private void btnVoltarHortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarHortaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarHortaActionPerformed

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        // TODO add your handling code here:
        if(!getPosicaoTabelaItem().equals("-1")){
            
            String[] options = { "Sim", "Não" };
            
            int deletar = JOptionPane.showOptionDialog(
                 rootPane,
                 "Tem certeza que deseja excluir as informações dessa planta?\n(essa ação não pode ser desfeita)", 
                 "Exclusão de planta(cultivo)", 
                 JOptionPane.DEFAULT_OPTION, 
                 JOptionPane.QUESTION_MESSAGE, 
                 null, 
                 options, 
                 options[0]
              
            );
            
            if (deletar == 0){
                DAO.excluir(DadoItem.class,  getPosicaoTabelaItem());
                iniciaTabelaItem();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma planta!");
        }
    }//GEN-LAST:event_btnExcluirItemActionPerformed

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        // TODO add your handling code here:
        if(!campoVazioItem()){
            
            DadoItem item = new DadoItem();
            item.setNomeItem(txtNomeItem.getText());
            item.setQuantidadeItem(Integer.parseInt(txtQuantidade.getText()));
            item.setPrecoItem(Double.parseDouble(txtPreco.getText()));
            
            double precoItem = Double.parseDouble(txtPreco.getText());
            int quantidadeItem = Integer.parseInt(txtQuantidade.getText());
            double precoTotalItem = precoItem * quantidadeItem;
            
            item.setPrecoItemTotal(precoTotalItem);

            try{
                DAO itemDao = new DAO();
                itemDao.cadastrar(item);
                JOptionPane.showMessageDialog(rootPane, "ItemCadastrado!");
                iniciaTabelaItem();

            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao cadastrar a planta:\n" + e.getMessage());
            }
        }   
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void btnVerDescriçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDescriçãoActionPerformed
        // TODO add your handling code here:
        String posicaoTabelaItem = getPosicaoTabelaItem();

        if (!posicaoTabelaItem.equals("-1")) {
            DadoItem itemSelecionado = DAO.obterPorId(DadoItem.class, posicaoTabelaItem);
            if(itemSelecionado.getDescricaoItem()==null){
                JOptionPane.showMessageDialog(null, "Ainda não foi adicionada uma descrição para este item.\nVocê pode fazer isso clicando no botão 'Alterar dados'");                
            }else{
                JOptionPane.showMessageDialog(null, "Descrição do item:" + itemSelecionado.getDescricaoItem());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma planta!");
        } 
    }//GEN-LAST:event_btnVerDescriçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnAlterarItem;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnVerDescrição;
    private javax.swing.JButton btnVoltarHorta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblItem;
    private javax.swing.JTextField txtNomeItem;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

private boolean campoVazioItem(){

    boolean empty = true; 

    if(txtNomeItem.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Nome do item não pode estar vazio.");    
    } else if(txtQuantidade.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Informar a quantidade do item!");   
    } else if(txtPreco.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Informar o preço do item!");   
    } else{
         empty = false;
    }
     return empty;    
    }

public static String getPosicaoTabelaItem() {
    int rowIndex = tblItem.getSelectedRow();

    if (rowIndex == -1) {
        return "-1";
    } else {
        return String.valueOf(tblItem.getValueAt(rowIndex, 0));
    }
}

public static void iniciaTabelaItem(){
    try{
        DAO itemDao = new DAO();
        List<DadoItem> listaItem = itemDao.listar(DadoItem.class);
        preencheTabelaItem(listaItem);
    }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu uma falha:\n" + e.getMessage());
    }
}

public static void preencheTabelaItem(List<DadoItem> listaItem){
    String columns[] = {"Id", "Nome", "Quantidade", "Preço", "Preço total"};
    String dados[][] = new String[listaItem.size()][columns.length];
    int i=0;
    for(DadoItem d: listaItem){
        dados[i] = new String[]{
            String.valueOf(d.getId()),
            d.getNomeItem(),
            String.valueOf(d.getQuantidadeItem()),
            String.valueOf(d.getPrecoItem()),
            String.valueOf(d.getPrecoItemTotal())};
        i++;
        }
    DefaultTableModel tabelaItem = new DefaultTableModel(dados, columns);
    tblItem.setModel(tabelaItem);
    TableColumnModel columnModel = tblItem.getColumnModel();//essa linha e as próximas escondem a coluna id para a tabela ficar visualmente melhor
    columnModel.getColumn(0).setMinWidth(0);
    columnModel.getColumn(0).setMaxWidth(0);
    columnModel.getColumn(0).setWidth(0);
    }

public void geraAcessbilidadeItem(){

btnAlterarItem.setMnemonic(KeyEvent.VK_A);
btnExcluirItem.setMnemonic(KeyEvent.VK_E);
btnVoltarHorta.setMnemonic(KeyEvent.VK_V);
    
}

}
