package br.com.senac.hortadidatica.gui.Planta;


import br.com.senac.hortadidatica.persistencia.DAO;
import br.com.senac.hortadidatica.persistencia.DadoPlanta;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danilo
 */
public class telaPlanta extends javax.swing.JFrame {

    /**
     * Creates new form telaPlanta
     */
    
    //Passo A
    public static final String[] tableColumnsCultivo = {"Nome da planta", "Família"};
    
    //Passo A2
    public static DefaultTableModel tableModelCultivo = new DefaultTableModel(tableColumnsCultivo, 0);
    
    public telaPlanta() {
        initComponents();
        geraAcessbilidadePlanta();
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) {
            iniciaTabelaPlanta();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnCultivo = new javax.swing.JButton();
        btnExcluirPlanta = new javax.swing.JButton();
        btnPlantaCultivoVoltar = new javax.swing.JButton();
        btnDidatico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAdicionarPlanta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomePopular = new javax.swing.JTextField();
        txtFamilia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("INFORMAÇÕES DE PLANTAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu Plantas"));

        btnCultivo.setText("Dados de cultivo");
        btnCultivo.setToolTipText("Clique aqui para adicionar ou atualizar dados de cultivo de uma das plantas da tabela ao lado (Alt + C)");
        btnCultivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCultivoActionPerformed(evt);
            }
        });

        btnExcluirPlanta.setText("Excluir Planta");
        btnExcluirPlanta.setToolTipText("Clique aqui para excluir uma das plantas listadas ao lado (Alt + E)");
        btnExcluirPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPlantaActionPerformed(evt);
            }
        });

        btnPlantaCultivoVoltar.setText("Voltar");
        btnPlantaCultivoVoltar.setToolTipText("Voltar para a tela principal (Alt + V)");
        btnPlantaCultivoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantaCultivoVoltarActionPerformed(evt);
            }
        });

        btnDidatico.setText("Dados didáticos");
        btnDidatico.setToolTipText("Clique aqui para adicionar ou atualizar dados didáticos de uma das plantas da tabela ao lado (Alt + D)");
        btnDidatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDidaticoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Planta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setToolTipText("Adicione o nome popular e família da planta para iniciar um novo cadastro");

        btnAdicionarPlanta.setText("Adicionar");
        btnAdicionarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPlantaActionPerformed(evt);
            }
        });

        jLabel2.setLabelFor(txtNomePopular);
        jLabel2.setText("Nome popular:");

        jLabel3.setLabelFor(txtFamilia);
        jLabel3.setText("Família:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdicionarPlanta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomePopular, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtFamilia))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomePopular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnAdicionarPlanta)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCultivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlantaCultivoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDidatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCultivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDidatico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirPlanta)
                .addGap(55, 55, 55)
                .addComponent(btnPlantaCultivoVoltar)
                .addContainerGap())
        );

        tblPlanta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome popular", "Família"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPlanta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCultivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCultivoActionPerformed
        // TODO add your handling code here:
    String posicaoTabelaPlanta = getPosicaoTabelaPlanta();

    if(!posicaoTabelaPlanta.equals("-1")) {
        DadoPlanta plantaSelecionada = DAO.obterPorId(DadoPlanta.class, posicaoTabelaPlanta);

        telaPlantaCultivo TelaPlantaCultivo = new telaPlantaCultivo();

        TelaPlantaCultivo.txtNomeCultivo.setText(plantaSelecionada.getNomePlanta());
        TelaPlantaCultivo.txtEpocaCultivo.setText(plantaSelecionada.getEpocaPlanta());
        TelaPlantaCultivo.txtTempoCultivo.setText(String.valueOf(plantaSelecionada.getTempoPlanta()));
        TelaPlantaCultivo.txtIrrigacao.setText(plantaSelecionada.getIrrigacaoPlanta());
        TelaPlantaCultivo.txtIluminacao.setText(plantaSelecionada.getIluminacaoPlanta());
        TelaPlantaCultivo.txtNutricional.setText(plantaSelecionada.getNutricionalPlanta());
        TelaPlantaCultivo.txtObsCultivo.setText(plantaSelecionada.getObservacoesCultivo());

        TelaPlantaCultivo.setVisible(true);
    }else{
        JOptionPane.showMessageDialog(null, "Selecione uma planta!");
    }
        
    }//GEN-LAST:event_btnCultivoActionPerformed

    private void btnExcluirPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPlantaActionPerformed
        // TODO add your handling code here:
        //chamar método:GenericDao.excluir(OutroTipoDeObjeto.class, 5);
        if(!getPosicaoTabelaPlanta().equals("-1")){
            
            String[] options = { "Sim", "Não" };
            
            int deletar = JOptionPane.showOptionDialog(
                 rootPane,
                 "Tem certeza que deseja excluir as informações dessa planta?\n(essa ação não pode ser desfeita)", 
                 "Exclusão de planta(cultivo)", 
                 JOptionPane.DEFAULT_OPTION, 
                 JOptionPane.QUESTION_MESSAGE, 
                 null, 
                 options, 
                 options[0]
              
            );
            
            if (deletar == 0){
                DAO.excluir(DadoPlanta.class,  getPosicaoTabelaPlanta());
                iniciaTabelaPlanta();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma planta!");
        }
        
    }//GEN-LAST:event_btnExcluirPlantaActionPerformed

    private void btnPlantaCultivoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantaCultivoVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnPlantaCultivoVoltarActionPerformed

    private void btnDidaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDidaticoActionPerformed
        // TODO add your handling code here:
    String posicaoTabelaPlanta = getPosicaoTabelaPlanta();

    if (!posicaoTabelaPlanta.equals("-1")) {
        DadoPlanta plantaSelecionada = DAO.obterPorId(DadoPlanta.class, posicaoTabelaPlanta);

        telaPlantaDidatico TelaPlantaDidatico = new telaPlantaDidatico();

        TelaPlantaDidatico.txtNomeDidatico.setText(plantaSelecionada.getNomePlanta());       
        TelaPlantaDidatico.txtNomeCientifico.setText(plantaSelecionada.getNomeCientifico());
        TelaPlantaDidatico.txtDidatico.setText(plantaSelecionada.getDidatico());

        TelaPlantaDidatico.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Selecione uma planta!");
    }   
    
    }//GEN-LAST:event_btnDidaticoActionPerformed

    private void btnAdicionarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPlantaActionPerformed
        // TODO add your handling code here:
        
        if(!campoVazioPlanta()){
            
            DadoPlanta planta = new DadoPlanta();
            planta.setNomePlanta(txtNomePopular.getText());
            planta.setFamiliaPlanta(txtFamilia.getText());
            
            try{
                DAO plantaDao = new DAO();
                plantaDao.cadastrar(planta);
                JOptionPane.showMessageDialog(rootPane, "Planta cadastrada!");
                iniciaTabelaPlanta();

            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao cadastrar a planta:\n" + e.getMessage());
            }
        }    
     
    }//GEN-LAST:event_btnAdicionarPlantaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPlanta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPlanta;
    private javax.swing.JButton btnCultivo;
    private javax.swing.JButton btnDidatico;
    private javax.swing.JButton btnExcluirPlanta;
    private javax.swing.JButton btnPlantaCultivoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblPlanta;
    private javax.swing.JTextField txtFamilia;
    private javax.swing.JTextField txtNomePopular;
    // End of variables declaration//GEN-END:variables

private boolean campoVazioPlanta(){

    boolean empty = true; 

    if(txtNomePopular.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! O nome da planta deve ser preenchido!");    
    } else if(txtFamilia.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Informar a família da planta!");   
    } else{
         empty = false;
    }
     return empty;    
}
    
public static String getPosicaoTabelaPlanta() {
    int rowIndex = tblPlanta.getSelectedRow();

    if (rowIndex == -1) {
        return "-1";
    } else {
        return String.valueOf(tblPlanta.getValueAt(rowIndex, 0));
    }
}

public void iniciaTabelaPlanta(){
    try{
        DAO plantaDao = new DAO();
        List<DadoPlanta> listaPlanta = plantaDao.listar(DadoPlanta.class);
        preencheTabelaPlanta(listaPlanta);
    }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
    }
}

public void preencheTabelaPlanta(List<DadoPlanta> listaPlanta){
    String columns[] = {"Id", "Nome Popular", "Família"};
    String dados[][] = new String[listaPlanta.size()][columns.length];
    int i=0;
    for(DadoPlanta d: listaPlanta){
        dados[i] = new String[]{
            String.valueOf(d.getId()),
            d.getNomePlanta(),
            d.getFamiliaPlanta()};
        i++;
        }
    DefaultTableModel tabelaPlanta = new DefaultTableModel(dados, columns);
    tblPlanta.setModel(tabelaPlanta);
    TableColumnModel columnModel = tblPlanta.getColumnModel();//essa linha e as próximas escondem a coluna id para a tabela ficar visualmente melhor
    columnModel.getColumn(0).setMinWidth(0);
    columnModel.getColumn(0).setMaxWidth(0);
    columnModel.getColumn(0).setWidth(0);
    }


public void geraAcessbilidadePlanta(){

btnCultivo.setMnemonic(KeyEvent.VK_C);
btnDidatico.setMnemonic(KeyEvent.VK_D);
btnExcluirPlanta.setMnemonic(KeyEvent.VK_E);
btnPlantaCultivoVoltar.setMnemonic(KeyEvent.VK_V);
    
}
}
